# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Fermentable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ppg', models.FloatField(blank=True, null=True)),
                ('lovibond', models.FloatField(blank=True, null=True)),
                ('moisture', models.FloatField(blank=True, null=True)),
                ('diastatic_power', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('max_in_batch', models.FloatField(blank=True, null=True)),
                ('is_mashed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fermentables_from_country', to='brew_data.CountryCode')),
            ],
        ),
        migrations.CreateModel(
            name='FermentableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fermentable',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermentables_with_type', to='brew_data.FermentableType'),
        ),
    ]
