# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-31 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_data', '0003_auto_20161229_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('og_min', models.FloatField(blank=True, null=True)),
                ('og_max', models.FloatField(blank=True, null=True)),
                ('fg_min', models.FloatField(blank=True, null=True)),
                ('fg_max', models.FloatField(blank=True, null=True)),
                ('ibu_min', models.FloatField(blank=True, null=True)),
                ('ibu_max', models.FloatField(blank=True, null=True)),
                ('srm_min', models.FloatField(blank=True, null=True)),
                ('srm_max', models.FloatField(blank=True, null=True)),
                ('abv_min', models.FloatField(blank=True, null=True)),
                ('abv_max', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
