# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_data', '0004_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentable',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='hop',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='CountryCode',
        ),
    ]
