# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew_data', '0005_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FermentableInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], max_length=4, null=True)),
                ('color', models.FloatField(blank=True, null=True)),
                ('color_units', models.TextField(blank=True, choices=[('L', 'L'), ('SRM', 'SRM')], max_length=3, null=True)),
                ('ppg', models.FloatField(blank=True, null=True)),
                ('dry_yield_percent', models.FloatField(blank=True, null=True)),
                ('dry_yield_fine_grind_percent', models.FloatField(blank=True, null=True)),
                ('moisture_percent', models.FloatField(blank=True, null=True)),
                ('diastatic_power_lintner', models.FloatField(blank=True, null=True)),
                ('protein_percent', models.FloatField(blank=True, null=True)),
                ('soluble_protein_percent', models.FloatField(blank=True, null=True)),
                ('nitrogen_percent', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='diastatic_power',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='is_mashed',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='lovibond',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='max_in_batch',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='ppg',
        ),
        migrations.RemoveField(
            model_name='fermentable',
            name='protein',
        ),
        migrations.AddField(
            model_name='fermentable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fermentable',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brew_data.CountryCode'),
        ),
        migrations.AlterField(
            model_name='fermentable',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew_data.FermentableType'),
        ),
        migrations.AddField(
            model_name='fermentableinstance',
            name='fermentable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='brew_data.Fermentable'),
        ),
    ]
