# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew_data', '0009_fermentabletype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentableinstance',
            name='fermentable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='brew_data.Fermentable'),
        ),
    ]
