# Generated by Django 3.2.7 on 2021-09-03 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_grain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grain',
            name='alpha_amylase',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
