# Generated by Django 3.2.7 on 2021-10-27 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_grain_alpha_amylase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fermentablebase',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fermentabletype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='graintype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='fermentablebase',
            name='fermentability_percent',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='grain',
            order_with_respect_to='fermentable',
        ),
    ]
