# Generated by Django 3.2.7 on 2021-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_hopform_hopproduct_hopuse_hopvariety'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopform',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hopproduct',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hopuse',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hopvariety',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
