# Generated by Django 3.2.7 on 2021-10-27 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_alter_fermentablebase_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hopproduct',
            old_name='total_oil_mk_per_100g',
            new_name='total_oil_ml_per_100g',
        ),
        migrations.AddField(
            model_name='hopproduct',
            name='percent_lost_after_6_months',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
