# Generated by Django 4.1.7 on 2023-02-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0011_culture_cultureform_culturetype_flocculationlabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hopproduct',
            options={'verbose_name': 'Hop', 'verbose_name_plural': 'Hops'},
        ),
        migrations.RemoveField(
            model_name='fermentablebase',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='hopvariety',
            name='substitutes',
            field=models.ManyToManyField(blank=True, to='ingredients.hopvariety'),
        ),
        migrations.CreateModel(
            name='FermentableProductId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('fermentable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ids', to='ingredients.fermentablebase')),
            ],
        ),
    ]
