# Generated by Django 4.1.7 on 2023-02-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0012_alter_hopproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentablebase',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='FermentableProductId',
        ),
    ]
