# Generated by Django 4.1.7 on 2023-02-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0013_fermentablebase_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentabletype',
            name='value',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
