# Generated by Django 4.1.7 on 2023-02-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0014_fermentabletype_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origin',
            name='country',
        ),
        migrations.AddField(
            model_name='origin',
            name='country_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
