# Generated by Django 4.1.7 on 2023-02-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0016_rename_fan_ppm_grain_fan_mg_l'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grain',
            old_name='coarse_grind_potential_ppg',
            new_name='coarse_grind_potential_percent',
        ),
        migrations.RenameField(
            model_name='grain',
            old_name='fine_grind_potential_ppg',
            new_name='fine_grind_potential_percent',
        ),
    ]
