# Generated by Django 4.1.7 on 2023-02-27 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0017_rename_coarse_grind_potential_ppg_grain_coarse_grind_potential_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grain',
            name='half_percent',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
