# Generated by Django 4.1.7 on 2023-02-27 12:43

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0018_grain_half_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentablebase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fermentablebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
