# Generated by Django 4.1.7 on 2023-02-27 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0019_fermentablebase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentablebase',
            name='color_srm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='fermentablebase',
            name='potential_ppg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
